name = "DiscreteControllers"
uuid = "a8b12e34-5c67-89de-f012-345678901234"
authors = ["Min-Gu Yoo <mgyoo86@gmail.com>"]
version = "0.1.0"

[deps]
DiscretePIDs = "c1363496-6848-4723-8758-079b737f6baf"
HelpPlots = "5880b2e8-ad0a-48c9-bacd-30dc9c1357e0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
DiscreteControllersPlotsExt = ["Plots"]

[compat]
DiscretePIDs = "0.1"
HelpPlots = "1.1.0"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
